-- DEPRECATED: Professor class-photo bulk attendance was removed from the app.
-- Do not run this file for new projects.
--
-- To remove storage policies from an existing project, run instead:
--   supabase/remove-professor-class-photo-attendance.sql
