"use client";

import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type {
  Profile,
  ProfessorAssignment,
  Classroom,
  StudentGroup,
  GeneratedTimetable,
  TimetableEntry,
} from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import {
  Loader2,
  Wand2,
  Check,
  X,
  Calendar,
  Clock,
  AlertTriangle,
  Trash2,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { toast } from "sonner";
import { DatePicker } from "@/components/ui/date-picker";
import { TIMETABLE_SLOTS, TIMETABLE_SLOT_CODES, inferSlotCodeFromStartTime } from "@/lib/timetable-slots";

const DAY_NAMES = ["", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

/** Fallback when a CSV row has no `max_hours_per_day` (legacy data). */
const DEFAULT_MAX_HOURS_PER_DAY = 4;

function maxHoursPerDayFromAssignments(assignments: ProfessorAssignment[]): number {
  if (assignments.length === 0) return DEFAULT_MAX_HOURS_PER_DAY;
  return Math.max(
    ...assignments.map((a) => Math.max(1, a.max_hours_per_day ?? DEFAULT_MAX_HOURS_PER_DAY))
  );
}

const SLOT_COLORS = [
  "bg-primary/10 border-primary/30 text-primary",
  "bg-accent/15 border-accent/30 text-accent-foreground",
  "bg-purple-100 border-purple-300 text-purple-900",
  "bg-orange-100 border-orange-300 text-orange-900",
  "bg-pink-100 border-pink-300 text-pink-900",
  "bg-teal-100 border-teal-300 text-teal-900",
  "bg-indigo-100 border-indigo-300 text-indigo-900",
  "bg-amber-100 border-amber-300 text-amber-900",
  "bg-cyan-100 border-cyan-300 text-cyan-900",
  "bg-rose-100 border-rose-300 text-rose-900",
];

interface ScheduleSlot {
  subject: string;
  professorEmail: string;
  professorName: string;
  studentGroupId: string;
  studentGroupName: string;
  classroomId: string;
  classroomName: string;
  eventDate?: string;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  /** S1–S7 when generated by the LLM */
  slotCode?: string;
}

export function TimetableGenerator({ profile }: { profile: Profile }) {
  const [profAssignments, setProfAssignments] = useState<ProfessorAssignment[]>([]);
  const [classrooms, setClassrooms] = useState<Classroom[]>([]);
  const [studentGroups, setStudentGroups] = useState<StudentGroup[]>([]);
  const [professors, setProfessors] = useState<Profile[]>([]);
  const [timetables, setTimetables] = useState<GeneratedTimetable[]>([]);
  const [loading, setLoading] = useState(true);

  const [selectedTerm, setSelectedTerm] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [generating, setGenerating] = useState(false);

  const [generatedSlots, setGeneratedSlots] = useState<ScheduleSlot[]>([]);
  const [showPreview, setShowPreview] = useState(false);
  const [saving, setSaving] = useState(false);
  const [genErrors, setGenErrors] = useState<string[]>([]);
  const [llmNotes, setLlmNotes] = useState("");

  const [viewTimetableId, setViewTimetableId] = useState<string | null>(null);
  const [viewEntries, setViewEntries] = useState<TimetableEntry[]>([]);
  const [viewLoading, setViewLoading] = useState(false);
  const [approving, setApproving] = useState(false);

  const [expandedTimetable, setExpandedTimetable] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    const supabase = createClient();
    const [paRes, crRes, sgRes, prRes, ttRes] = await Promise.all([
      supabase.from("professor_assignments").select("*").order("term").order("subject"),
      supabase.from("classrooms").select("*").order("name"),
      supabase.from("student_groups").select("*").order("name"),
      supabase.from("profiles").select("*").eq("role", "professor").order("full_name"),
      supabase.from("generated_timetables").select("*").order("created_at", { ascending: false }),
    ]);

    if (paRes.data) setProfAssignments(paRes.data);
    if (crRes.data) setClassrooms(crRes.data);
    if (sgRes.data) setStudentGroups(sgRes.data);
    if (prRes.data) setProfessors(prRes.data);
    if (ttRes.data) setTimetables(ttRes.data);
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const allTerms = [...new Set(profAssignments.map((a) => a.term))].sort();

  useEffect(() => {
    if (allTerms.length > 0 && !selectedTerm) {
      setSelectedTerm(allTerms[0]);
    }
  }, [allTerms, selectedTerm]);

  async function generateTimetable() {
    setGenerating(true);
    setGenErrors([]);
    setGeneratedSlots([]);

    const termAssignments = profAssignments.filter((a) => a.term === selectedTerm);
    if (termAssignments.length === 0) {
      const m = "No professor assignments found for this term.";
      setGenErrors([m]);
      toast.error(m);
      setGenerating(false);
      return;
    }

    if (!startDate || !endDate) {
      const m = "Please set term start and end dates.";
      setGenErrors([m]);
      toast.error(m);
      setGenerating(false);
      return;
    }

    try {
      const res = await fetch("/api/timetable/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "same-origin",
        body: JSON.stringify({
          term: selectedTerm,
          startDate,
          endDate,
        }),
      });

      let data: Record<string, unknown> = {};
      const rawText = await res.text();
      try {
        data = rawText ? (JSON.parse(rawText) as Record<string, unknown>) : {};
      } catch {
        const m = `Server returned non-JSON (${res.status}). Check the terminal / network tab.`;
        setGenErrors([m, rawText.slice(0, 500)]);
        toast.error("Invalid response from server");
        setShowPreview(true);
        return;
      }

      if (!res.ok) {
        const msg =
          typeof data.error === "string"
            ? data.error
            : `Failed to generate timetable (${res.status})`;
        const extra = Array.isArray(data.validationErrors)
          ? (data.validationErrors as string[])
          : [];
        const lines = [msg, ...extra].filter(Boolean);
        setGenErrors(lines);
        setLlmNotes(typeof data.notes === "string" ? data.notes : "");
        toast.error(lines[0] ?? msg);
        setGeneratedSlots([]);
        setShowPreview(true);
        return;
      }

      const slots = (data.slots ?? []) as ScheduleSlot[];
      setGeneratedSlots(slots);
      setGenErrors([]);
      setLlmNotes(typeof data.modelNotes === "string" ? data.modelNotes : "");
      setShowPreview(true);

      if (slots.length === 0) {
        toast.warning("Generation finished but returned no sessions. Check OPENAI_API_KEY and try again.");
        setGenErrors([
          "The model returned an empty schedule. Try again, or check API logs / OPENAI_TIMETABLE_MODEL.",
        ]);
      } else {
        toast.success(`Generated ${slots.length} term session(s)`);
      }
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      setGenErrors([`Request failed: ${msg}`]);
      setGeneratedSlots([]);
      toast.error(msg);
      setShowPreview(true);
    } finally {
      setGenerating(false);
    }
  }

  async function saveTimetable() {
    if (generatedSlots.length === 0) return;
    setSaving(true);

    const supabase = createClient();

    const termAssignmentsForSave = profAssignments.filter((a) => a.term === selectedTerm);
    const metaMaxHoursPerDay = maxHoursPerDayFromAssignments(termAssignmentsForSave);

    const { data: tt, error: ttErr } = await supabase
      .from("generated_timetables")
      .insert({
        term: selectedTerm,
        start_date: startDate,
        end_date: endDate,
        max_hours_per_day: metaMaxHoursPerDay,
        status: "draft",
        generated_by: profile.id,
      })
      .select()
      .single();

    if (ttErr || !tt) {
      toast.error("Failed to save timetable: " + (ttErr?.message ?? "Unknown error"));
      setSaving(false);
      return;
    }

    const profByEmail: Record<string, Profile> = {};
    for (const p of professors) profByEmail[p.email] = p;

    const entries = generatedSlots.map((slot) => ({
      timetable_id: tt.id,
      professor_id: profByEmail[slot.professorEmail]?.id ?? null,
      professor_email: slot.professorEmail,
      subject: slot.subject,
      student_group_id: slot.studentGroupId,
      classroom_id: slot.classroomId,
      event_date: slot.eventDate ?? null,
      day_of_week: slot.dayOfWeek,
      start_time: slot.startTime,
      end_time: slot.endTime,
    }));

    const { error: entryErr } = await supabase
      .from("timetable_entries")
      .insert(entries);

    if (entryErr) {
      toast.error("Failed to save timetable entries: " + entryErr.message);
      await supabase.from("generated_timetables").delete().eq("id", tt.id);
      setSaving(false);
      return;
    }

    toast.success("Timetable saved as draft! Review and approve it below.");
    setSaving(false);
    setShowPreview(false);
    setGeneratedSlots([]);
    fetchData();
  }

  async function viewTimetable(id: string) {
    setViewTimetableId(id);
    setViewLoading(true);

    const supabase = createClient();
    const { data } = await supabase
      .from("timetable_entries")
      .select("*, professor:profiles!timetable_entries_professor_id_fkey(*), student_group:student_groups(*), classroom:classrooms(*)")
      .eq("timetable_id", id)
      .order("event_date", { ascending: true, nullsFirst: false })
      .order("day_of_week")
      .order("start_time");

    if (data) setViewEntries(data);
    setViewLoading(false);
  }

  async function approveTimetable(timetableId: string) {
    setApproving(true);
    const supabase = createClient();

    const { data: entries } = await supabase
      .from("timetable_entries")
      .select("*")
      .eq("timetable_id", timetableId);

    if (!entries || entries.length === 0) {
      toast.error("No entries found for this timetable.");
      setApproving(false);
      return;
    }

    const tt = timetables.find((t) => t.id === timetableId);
    if (!tt) {
      toast.error("Timetable not found.");
      setApproving(false);
      return;
    }

    // Resolve professor IDs from emails (best-effort; null if not signed up yet)
    const uniqueEmails = [...new Set(entries.map((e) => e.professor_email))];
    const { data: profProfiles } = await supabase
      .from("profiles")
      .select("id, email")
      .eq("role", "professor")
      .in("email", uniqueEmails);

    const emailToId: Record<string, string | null> = {};
    for (const e of uniqueEmails) emailToId[e] = null;
    for (const p of profProfiles ?? []) {
      emailToId[p.email] = p.id;
    }

    const unresolved = uniqueEmails.filter((e) => !emailToId[e]);
    if (unresolved.length > 0) {
      toast.info(
        `${unresolved.length} professor(s) haven't signed up yet (${unresolved.join(", ")}). Events will appear in their dashboards once they create accounts.`
      );
    }

    // Generate calendar requests from entries.
    // For new term schedules, event_date is present and used directly.
    // For legacy weekly schedules, expand by weekday across the term range.
    const sDate = new Date(tt.start_date);
    const eDate = new Date(tt.end_date);

    const calendarRows: Array<{
      professor_id: string | null;
      professor_email: string;
      title: string;
      description: string;
      student_group_id: string | null;
      classroom_id: string | null;
      event_date: string;
      start_time: string;
      end_time: string;
      status: string;
      reviewed_by: string;
    }> = [];

    for (const entry of entries) {
      const profId = emailToId[entry.professor_email] ?? null;
      if (entry.event_date) {
        calendarRows.push({
          professor_id: profId,
          professor_email: entry.professor_email,
          title: `${entry.subject} (Timetable)`,
          description: `Auto-generated from timetable for ${tt.term}`,
          student_group_id: entry.student_group_id,
          classroom_id: entry.classroom_id,
          event_date: entry.event_date,
          start_time: entry.start_time,
          end_time: entry.end_time,
          status: "approved",
          reviewed_by: profile.id,
        });
        continue;
      }

      const current = new Date(sDate);
      while (current <= eDate) {
        // JS getDay(): 0=Sun, 1=Mon... our day_of_week: 1=Mon...6=Sat
        const jsDay = current.getDay();
        if (jsDay === entry.day_of_week) {
          calendarRows.push({
            professor_id: profId,
            professor_email: entry.professor_email,
            title: `${entry.subject} (Timetable)`,
            description: `Auto-generated from timetable for ${tt.term}`,
            student_group_id: entry.student_group_id,
            classroom_id: entry.classroom_id,
            event_date: current.toISOString().split("T")[0],
            start_time: entry.start_time,
            end_time: entry.end_time,
            status: "approved",
            reviewed_by: profile.id,
          });
        }
        current.setDate(current.getDate() + 1);
      }
    }

    if (calendarRows.length === 0) {
      toast.error("No calendar events to create for the given date range.");
      setApproving(false);
      return;
    }

    // Insert in batches of 100
    for (let i = 0; i < calendarRows.length; i += 100) {
      const batch = calendarRows.slice(i, i + 100);
      const { error } = await supabase.from("calendar_requests").insert(batch);
      if (error) {
        toast.error(`Failed to create calendar events (batch ${Math.floor(i / 100) + 1}): ${error.message}`);
        setApproving(false);
        return;
      }
    }

    // Mark timetable as approved
    await supabase
      .from("generated_timetables")
      .update({ status: "approved", approved_by: profile.id, updated_at: new Date().toISOString() })
      .eq("id", timetableId);

    toast.success(`Timetable approved! ${calendarRows.length} calendar events created.`);
    setApproving(false);
    setViewTimetableId(null);
    fetchData();
  }

  async function deleteTimetable(id: string) {
    if (!window.confirm("Delete this timetable? This will remove the timetable and all its entries (but not any already-approved calendar events).")) return;
    const supabase = createClient();
    const { error } = await supabase.from("generated_timetables").delete().eq("id", id);
    if (error) {
      toast.error("Failed to delete: " + error.message);
      return;
    }
    toast.success("Timetable deleted.");
    fetchData();
  }

  const subjectColorMap: Record<string, string> = {};
  let colorIdx = 0;
  function getSubjectColor(subject: string): string {
    if (!subjectColorMap[subject]) {
      subjectColorMap[subject] = SLOT_COLORS[colorIdx % SLOT_COLORS.length];
      colorIdx++;
    }
    return subjectColorMap[subject];
  }

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const termAssignmentCount = profAssignments.filter((a) => a.term === selectedTerm).length;

  return (
    <div className="space-y-6">
      {/* Generator form */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5" />
            Generate Timetable
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {profAssignments.length === 0 ? (
            <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
              <AlertTriangle className="h-4 w-4 inline mr-2" />
              No professor assignments uploaded yet. Go to <strong>Professor Assignments</strong> tab to upload a CSV first.
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>
                    Term
                    <span className="text-destructive">*</span>
                  </Label>
                  <select
                    className="flex h-9 w-full rounded-lg border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    value={selectedTerm}
                    onChange={(e) => setSelectedTerm(e.target.value)}
                    required
                  >
                    <option value="">Select...</option>
                    {allTerms.map((t) => (
                      <option key={t} value={t}>{t}</option>
                    ))}
                  </select>
                  <p className="text-xs text-muted-foreground">
                    {termAssignmentCount} assignments · max hours/day from CSV per course
                  </p>
                </div>
                <div className="space-y-2">
                  <Label>
                    Term Start Date
                    <span className="text-destructive">*</span>
                  </Label>
                  <DatePicker
                    value={startDate}
                    onChange={setStartDate}
                    min={new Date().toISOString().split("T")[0]}
                    placeholder="Pick start date"
                  />
                </div>
                <div className="space-y-2">
                  <Label>
                    Term End Date
                    <span className="text-destructive">*</span>
                  </Label>
                  <DatePicker
                    value={endDate}
                    onChange={setEndDate}
                    min={startDate || new Date().toISOString().split("T")[0]}
                    placeholder="Pick end date"
                    disabled={!startDate}
                  />
                </div>
              </div>

              <Button
                onClick={generateTimetable}
                disabled={generating || !selectedTerm || !startDate || !endDate}
                className="gap-2"
              >
                {generating ? (
                  <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</>
                ) : (
                  <><Wand2 className="h-4 w-4" /> Generate Timetable</>
                )}
              </Button>
            </>
          )}
        </CardContent>
      </Card>

      {/* Generated preview or error panel */}
      {showPreview && (
        <Card
          className={
            generatedSlots.length === 0 && genErrors.length > 0
              ? "border-destructive/40"
              : "border-primary/30"
          }
        >
          <CardHeader>
            <div className="flex items-start justify-between">
              <div>
                <CardTitle>
                  {generatedSlots.length === 0 && genErrors.length > 0
                    ? "Timetable generation issue"
                    : "Generated Timetable Preview"}
                </CardTitle>
                <CardDescription>
                  {generatedSlots.length > 0 ? (
                    <>
                      {generatedSlots.length} term session(s) for {selectedTerm}
                      {llmNotes ? ` — ${llmNotes}` : ""}
                    </>
                  ) : genErrors.length > 0 ? (
                    <>Fix the issues below and try Generate again.</>
                  ) : (
                    <>No sessions in this preview.</>
                  )}
                </CardDescription>
              </div>
              <div className="flex gap-2">
                <Button variant="outline" onClick={() => setShowPreview(false)}>
                  Cancel
                </Button>
                <Button onClick={saveTimetable} disabled={saving || generatedSlots.length === 0} className="gap-2">
                  {saving ? (
                    <><Loader2 className="h-4 w-4 animate-spin" /> Saving...</>
                  ) : (
                    <><Check className="h-4 w-4" /> Save as Draft</>
                  )}
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {genErrors.length > 0 && (
              <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 space-y-1">
                <p className="text-sm font-medium text-amber-800 flex items-center gap-1.5">
                  <AlertTriangle className="h-4 w-4" />
                  {genErrors.length} scheduling issue(s)
                </p>
                {genErrors.map((err, i) => (
                  <p key={i} className="text-xs text-amber-700 whitespace-pre-wrap break-words">
                    {err}
                  </p>
                ))}
              </div>
            )}

            {generatedSlots.length > 0 ? (
              <SlotWeeklyGrid slots={generatedSlots} getSubjectColor={getSubjectColor} />
            ) : (
              !genErrors.length && (
                <p className="text-sm text-muted-foreground">No slots to display.</p>
              )
            )}
          </CardContent>
        </Card>
      )}

      {/* Existing timetables */}
      {timetables.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              Saved Timetables
            </CardTitle>
            <CardDescription>{timetables.length} timetable(s)</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {timetables.map((tt) => (
              <div key={tt.id} className="rounded-lg border p-4 space-y-3">
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-medium">{tt.term}</span>
                      <Badge
                        className={
                          tt.status === "approved"
                            ? "bg-accent/15 text-accent-foreground"
                            : tt.status === "rejected"
                            ? "bg-destructive/10 text-destructive"
                            : "bg-yellow-100 text-yellow-800"
                        }
                        variant="outline"
                      >
                        {tt.status.charAt(0).toUpperCase() + tt.status.slice(1)}
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">
                      {tt.start_date} to {tt.end_date} · CSV max (highest row): {tt.max_hours_per_day}h/day
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        if (expandedTimetable === tt.id) {
                          setExpandedTimetable(null);
                        } else {
                          setExpandedTimetable(tt.id);
                          viewTimetable(tt.id);
                        }
                      }}
                      className="gap-1"
                    >
                      {expandedTimetable === tt.id ? (
                        <><ChevronUp className="h-3.5 w-3.5" /> Hide</>
                      ) : (
                        <><ChevronDown className="h-3.5 w-3.5" /> View</>
                      )}
                    </Button>
                    {tt.status === "draft" && (
                      <Button
                        size="sm"
                        onClick={() => viewTimetable(tt.id).then(() => setViewTimetableId(tt.id))}
                        className="gap-1 bg-primary hover:bg-primary/90"
                      >
                        <Check className="h-3.5 w-3.5" /> Review & Approve
                      </Button>
                    )}
                    {tt.status === "draft" && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => deleteTimetable(tt.id)}
                        className="gap-1 text-destructive hover:text-destructive hover:bg-destructive/10"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    )}
                  </div>
                </div>

                {expandedTimetable === tt.id && (
                  <div className="mt-3">
                    {viewLoading ? (
                      <div className="flex justify-center py-4">
                        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                      </div>
                    ) : (
                      <SlotWeeklyGrid
                        slots={viewEntries.map((e) => ({
                          subject: e.subject,
                          professorEmail: e.professor_email,
                          professorName: e.professor?.full_name ?? e.professor_email,
                          studentGroupId: e.student_group_id ?? "",
                          studentGroupName: e.student_group?.name ?? "",
                          classroomId: e.classroom_id ?? "",
                          classroomName: e.classroom?.name ?? "",
                          dayOfWeek: e.day_of_week,
                          startTime: e.start_time,
                          endTime: e.end_time,
                        }))}
                        getSubjectColor={getSubjectColor}
                      />
                    )}
                  </div>
                )}
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {/* Approve dialog — wide layout; default DialogContent uses sm:max-w-sm which was crushing this */}
      <Dialog open={!!viewTimetableId} onOpenChange={(open) => { if (!open) setViewTimetableId(null); }}>
        <DialogContent
          showCloseButton={false}
          className="flex h-[min(92vh,960px)] w-[min(96rem,calc(100vw-1.5rem))] max-w-none flex-col gap-0 overflow-hidden p-0 sm:max-w-[min(96rem,calc(100vw-1.5rem))]"
        >
          <div className="flex shrink-0 items-start justify-between gap-4 border-b px-5 pt-5 pb-4 pr-14">
            <DialogHeader className="space-y-1.5 text-left">
              <DialogTitle>Review Timetable</DialogTitle>
              <DialogDescription>
                Approving will create calendar events for the full term.
              </DialogDescription>
            </DialogHeader>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="absolute top-3 right-3 shrink-0"
              onClick={() => setViewTimetableId(null)}
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>

          {viewLoading ? (
            <div className="flex flex-1 items-center justify-center py-16">
              <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <>
              <div className="min-h-0 flex-1 overflow-y-auto overflow-x-auto px-5 py-4">
                <SlotWeeklyGrid
                  slots={viewEntries.map((e) => ({
                    subject: e.subject,
                    professorEmail: e.professor_email,
                    professorName: e.professor?.full_name ?? e.professor_email,
                    studentGroupId: e.student_group_id ?? "",
                    studentGroupName: e.student_group?.name ?? "",
                    classroomId: e.classroom_id ?? "",
                    classroomName: e.classroom?.name ?? "",
                    dayOfWeek: e.day_of_week,
                    startTime: e.start_time,
                    endTime: e.end_time,
                  }))}
                  getSubjectColor={getSubjectColor}
                />
              </div>
              <div className="flex shrink-0 flex-col gap-3 border-t bg-muted/40 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
                <p className="text-sm text-muted-foreground">
                  {viewEntries.length} saved session(s) will be created in calendars when approved.
                </p>
                <div className="flex flex-wrap justify-end gap-2">
                  <Button variant="outline" onClick={() => setViewTimetableId(null)}>
                    Cancel
                  </Button>
                  {timetables.find((t) => t.id === viewTimetableId)?.status === "draft" && (
                    <Button
                      onClick={() => approveTimetable(viewTimetableId!)}
                      disabled={approving}
                      className="gap-2 bg-primary hover:bg-primary/90"
                    >
                      {approving ? (
                        <><Loader2 className="h-4 w-4 animate-spin" /> Approving...</>
                      ) : (
                        <><Check className="h-4 w-4" /> Approve & Create Events</>
                      )}
                    </Button>
                  )}
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}

function SlotWeeklyGrid({
  slots,
  getSubjectColor,
}: {
  slots: ScheduleSlot[];
  getSubjectColor: (subject: string) => string;
}) {
  function slotFor(s: ScheduleSlot): string {
    if (s.slotCode) return s.slotCode;
    return inferSlotCodeFromStartTime(s.startTime) ?? "?";
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-xs border-collapse min-w-[760px] border border-border rounded-lg overflow-hidden">
        <thead>
          <tr className="bg-muted/50 border-b">
            <th className="p-2 text-left font-medium w-10">Slot</th>
            <th className="p-2 text-left font-medium w-36">Time</th>
            {[1, 2, 3, 4, 5, 6].map((d) => (
              <th key={d} className="p-2 text-center font-medium border-l min-w-[130px]">
                {DAY_NAMES[d]}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {TIMETABLE_SLOT_CODES.map((code) => {
            const t = TIMETABLE_SLOTS[code];
            return (
              <tr key={code} className="border-b border-border/80">
                <td className="p-2 font-mono font-semibold align-top">{code}</td>
                <td className="p-2 text-muted-foreground whitespace-nowrap align-top">
                  {t.start}–{t.end}
                </td>
                {[1, 2, 3, 4, 5, 6].map((d) => {
                  const cell = slots.filter(
                    (s) => s.dayOfWeek === d && slotFor(s) === code
                  );
                  return (
                    <td key={d} className="border-l p-1 align-top">
                      {cell.map((slot, idx) => (
                        <div
                          key={idx}
                          className={`rounded px-1.5 py-1 border mb-1 last:mb-0 ${getSubjectColor(slot.subject)}`}
                          title={`${slot.subject}\nProf. ${slot.professorName}\n${slot.classroomName}\n${slot.studentGroupName}\n${slot.startTime}–${slot.endTime}`}
                        >
                          <div className="font-semibold truncate">{slot.subject}</div>
                          <div className="truncate opacity-80">{slot.classroomName}</div>
                          <div className="truncate opacity-70 text-[10px]">
                            {slot.professorName.split(" ").pop()}
                          </div>
                        </div>
                      ))}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>

      <div className="flex flex-wrap gap-2 mt-3 pt-3 border-t">
        {[...new Set(slots.map((s) => s.subject))].sort().map((subject) => (
          <span
            key={subject}
            className={`inline-flex items-center rounded px-2 py-0.5 text-xs font-medium border ${getSubjectColor(subject)}`}
          >
            {subject}
          </span>
        ))}
      </div>
    </div>
  );
}
