import type { Metadata } from "next";
import Link from "next/link";
import { NucleusWordmark } from "@/components/nucleus-wordmark";

export const metadata: Metadata = {
  title: "Privacy Policy — The Nucleus",
  description:
    "Privacy Policy for The Nucleus — aligned with the Digital Personal Data Protection Act, 2023 (DPDPA).",
};

const EFFECTIVE_DATE = "18 April 2026";
const CONTACT_EMAIL = "info.thenucleus@gmail.com";
const COMPANY_NAME = "The Nucleus";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-card/80 backdrop-blur-sm">
        <div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2 no-underline text-foreground">
            <NucleusWordmark decorative size="sm" />
          </Link>
          <Link href="/terms" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            Terms of Service
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-14">
        <p className="text-sm text-muted-foreground mb-2">Last updated: {EFFECTIVE_DATE}</p>
        <h1 className="font-display text-4xl font-bold tracking-tight mb-4">Privacy Policy</h1>
        <p className="text-muted-foreground mb-10 text-lg leading-relaxed">
          This Privacy Policy explains how {COMPANY_NAME} (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) — acting
          as a <strong className="text-foreground">Data Fiduciary</strong> under the Digital Personal Data Protection
          Act, 2023 (<strong className="text-foreground">DPDPA</strong>) — collects, uses, stores, and protects your
          personal data when you use The Nucleus mobile application and web platform. You are the{" "}
          <strong className="text-foreground">Data Principal</strong> in relation to your personal data. This policy
          is consistent with the DPDPA, the Information Technology Act, 2000, and applicable rules (including
          reasonable security practices for handling digital information). Where app stores require disclosures, we
          also describe categories of data in a clear, comparable form below.
        </p>

        <DataTable />

        <Section title="1. Information We Collect">
          <Subheading>1.1 Account Information</Subheading>
          <p>
            When you create an account we collect your full name, institutional email address, mobile phone number,
            role (student / professor / admin), and password (stored only as a hashed credential — we never see
            plaintext passwords). If you sign in with Google, we receive your name and email from Google.
          </p>

          <Subheading>1.2 Biometric Data (students only)</Subheading>
          <p>
            For student users who opt in to face-based attendance, we collect:
          </p>
          <ul className="mt-2 list-disc pl-6 space-y-1">
            <li>Facial photographs taken by the front camera of your device.</li>
            <li>
              Numerical representations of your face geometry, generated by an on-server machine-learning model and
              stored alongside your user ID.
            </li>
          </ul>
          <p className="mt-3">
            Biometric data is processed exclusively for the purpose of identity verification during attendance
            sessions. It is encrypted and access-controlled, is not used for advertising or unrelated profiling, is not
            used to build individual-level marketing or analytics profiles, and is not sold to any third party.
          </p>

          <Subheading>1.3 Identity documents (when required by your institution)</Subheading>
          <p>
            Where an educational institution configures the platform to collect identity documents (for example,
            government-issued identification or a student ID card), we process that information only for identity
            verification and fraud prevention as directed by the institution. Such documents are stored with restricted
            access and are not used for advertising.
          </p>

          <Subheading>1.4 Device Permissions</Subheading>
          <ul className="mt-2 list-disc pl-6 space-y-1">
            <li>
              <strong className="text-foreground">Camera</strong> — used only during explicit user-initiated face
              registration or attendance checks. No background camera access is requested.
            </li>
            <li>
              <strong className="text-foreground">Location</strong> — requested (with your permission) to assist
              Wi-Fi proximity verification for attendance. Coarse or fine location is checked in-session and not
              stored persistently.
            </li>
            <li>
              <strong className="text-foreground">Bluetooth</strong> — used on some campus networks for proximity
              detection. BLE scanning data is not stored on our servers.
            </li>
          </ul>

          <Subheading>1.5 Usage Data</Subheading>
          <p>
            We collect standard server logs (IP address, device type, OS version, app version, timestamps) for
            security monitoring and debugging. These are retained for 90 days and then deleted.
          </p>
        </Section>

        <Section title="2. How We Use Your Information">
          <ul className="list-disc pl-6 space-y-2">
            <li>Authenticate you and manage your account session.</li>
            <li>Verify your identity during attendance marking using your stored face profile data.</li>
            <li>
              Verify identity using documents or checks your institution enables, where applicable, and detect or
              prevent fraudulent account activity.
            </li>
            <li>Display your schedule, exam timetable, and campus calendar.</li>
            <li>Send important account notifications (e.g. email confirmation, password reset).</li>
            <li>Comply with legal obligations and prevent fraudulent activity.</li>
            <li>Improve the platform through aggregated, anonymised analytics.</li>
          </ul>
          <p className="mt-3">We do not use your data to serve advertisements.</p>
        </Section>

        <Section title="3. Legal basis and consent">
          <p>
            Under the DPDPA, we process your personal data on the basis of your{" "}
            <strong className="text-foreground">voluntary, specific, informed, unconditional, and clear</strong>{" "}
            consent where the law requires consent — in particular for account creation, optional Google sign-in, and
            any biometric face data used for attendance. You may withdraw consent for optional processing (including
            biometric enrolment) at any time; withdrawal does not affect the lawfulness of processing that already
            occurred before withdrawal.
          </p>
          <p className="mt-3">
            We also rely on processing that is necessary to provide the service you asked for (for example,
            authenticating you, displaying your timetable, and keeping the platform secure). We do not use your
            personal data for purposes that are incompatible with these terms without obtaining fresh consent where
            the DPDPA requires it.
          </p>
          <p className="mt-3 text-sm text-muted-foreground border border-border rounded-lg p-4">
            <strong className="text-foreground">Note:</strong> Certain categories of data (such as derived face data
            used to verify attendance) are treated with additional care and are collected only where you have agreed
            through in-app flows and this policy.
          </p>
        </Section>

        <Section title="4. Data Sharing">
          <p>We share personal data only with:</p>
          <ul className="mt-3 list-disc pl-6 space-y-2">
            <li>
              <strong className="text-foreground">Hosted infrastructure</strong> — our database, authentication, and
              file storage run on secure cloud services. Data may be stored in the region configured for your
              deployment.
            </li>
            <li>
              <strong className="text-foreground">Google</strong> — only if you choose Google sign-in. We receive
              your name and email; Google does not receive your biometric data.
            </li>
            <li>
              <strong className="text-foreground">Your school</strong> — attendance outcomes and related academic
              records (for example, present or absent status tied to classes) may be visible to authorised staff at
              your college or university for academic administration. We do not provide raw biometric photographs or
              numerical face templates to institutions for unrelated commercial use; processing of such data remains
              governed by this policy and your consent.
            </li>
          </ul>
          <p className="mt-3">We do not sell, rent, or trade personal data to any third party for commercial purposes.</p>
          <h3 className="font-semibold text-foreground mt-8 mb-1">Institutional deployment</h3>
          <p className="mt-2">
            When the platform is deployed or sponsored by an educational institution, the institution determines how
            attendance and academic records are used within its own policies. The institution is responsible for
            obtaining any consents required under applicable law (including for minors) before students or staff use
            certain features. {COMPANY_NAME} processes personal data to provide the services configured on the platform
            and as described in this policy.
          </p>
        </Section>

        <Section title="5. Data Retention">
          <ul className="list-disc pl-6 space-y-2">
            <li>Account data is retained for the duration of your active account plus 12 months after closure.</li>
            <li>
              Facial photographs and derived biometric data are deleted within 30 days of a biometric consent withdrawal
              or account deletion request.
            </li>
            <li>Attendance records are retained for the academic year plus 3 years for institutional compliance.</li>
            <li>Server logs are retained for 90 days.</li>
          </ul>
        </Section>

        <Section title="6. Security">
          <p>
            We implement industry-standard safeguards: TLS encryption in transit, AES-256 encryption at rest for
            stored files, row-level security policies on all database tables, and short-lived signed URLs for
            accessing stored photos. Access to biometric data is restricted to authenticated requests from your
            own account and authorised backend services. We maintain access logs for privileged operations where
            technically feasible and conduct periodic internal reviews of security configuration and access patterns.
          </p>
          <p className="mt-3">
            No method of transmission or storage is 100% secure. In the event of a personal data breach that is
            likely to affect your rights, we will take steps required under the DPDPA and related rules — including,
            where applicable, notifying the Data Protection Board of India and affected Data Principals in the manner
            and within the timelines the law prescribes.
          </p>
        </Section>

        <Section title="7. Your rights as a Data Principal (DPDPA)">
          <p>
            The DPDPA grants you rights including (where applicable) the following. We honour these requests subject to
            verification of your identity and any exceptions the law allows (for example, records we must keep for
            legal or academic compliance).
          </p>
          <ul className="mt-3 list-disc pl-6 space-y-2">
            <li>
              <strong className="text-foreground">Access and information</strong> — obtain a summary of your
              personal data being processed and the main purposes of processing.
            </li>
            <li>
              <strong className="text-foreground">Correction and updating</strong> — request correction of inaccurate,
              incomplete, or misleading personal data, or updating where it is incomplete.
            </li>
            <li>
              <strong className="text-foreground">Erasure</strong> — request erasure of your personal data where the
              law permits and we no longer need it for the purpose for which it was collected.
            </li>
            <li>
              <strong className="text-foreground">Grievance redressal</strong> — raise concerns about how we handle your
              personal data with us first; we will address grievances in line with DPDPA timelines once rules specify
              them, and in the meantime as promptly as practicable.
            </li>
            <li>
              <strong className="text-foreground">Nomination</strong> — where the DPDPA allows, you may nominate another
              person to exercise your rights in the event of your death or incapacity, in the manner prescribed when
              rules are notified.
            </li>
            <li>
              <strong className="text-foreground">Withdraw consent</strong> — where processing is based on your
              consent (including biometric enrolment), you may withdraw consent going forward.
            </li>
          </ul>
          <p className="mt-3">
            To exercise these rights or ask questions, email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-2">
              {CONTACT_EMAIL}
            </a>
            . We will respond without undue delay and, once Central Government rules fix a standard period, within that
            period.
          </p>
        </Section>

        <Section title="8. Children">
          <p>
            Under the DPDPA, a <strong className="text-foreground">child</strong> is an individual who has not
            completed eighteen years of age (subject to any age threshold the Central Government may notify for
            specific services). We do not knowingly collect or track personal data from young children for marketing.
            Where a school deploys The Nucleus for students who are children under the DPDPA, the school and parents or
            lawful guardians should ensure that any consent or authorisation required under applicable law is obtained
            before enrolment and use of biometric features. If you believe we have collected a child&apos;s personal
            data without appropriate authority, write to{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-2">
              {CONTACT_EMAIL}
            </a>
            ; we will review and, if appropriate, delete such data.
          </p>
        </Section>

        <Section title="9. Cookies and Local Storage">
          <p>
            The web platform uses browser local storage and session cookies for authentication. We do not use
            third-party tracking cookies or analytics cookies. A single,
            strictly-necessary session cookie is set upon login and cleared on logout.
          </p>
        </Section>

        <Section title="10. Changes to This Policy">
          <p>
            We may update this Privacy Policy to reflect changes in our practices or applicable law. Material
            changes will be communicated via in-app notice or email at least 14 days before taking effect.
            The &quot;last updated&quot; date at the top of this page indicates the most recent revision.
          </p>
        </Section>

        <Section title="11. Contact, grievance redressal, and the Data Protection Board">
          <p>
            For privacy questions, grievances, or to exercise your rights as a Data Principal, contact:{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-2">
              {CONTACT_EMAIL}
            </a>
          </p>
          <p className="mt-3">
            If you are not satisfied with our response, you may escalate your complaint to the{" "}
            <strong className="text-foreground">Data Protection Board of India</strong> once it is fully operational
            and the Central Government has prescribed the manner and form of complaints under the DPDPA. We will
            cooperate with the Board as required by law.
          </p>
          <p className="mt-3 text-sm text-muted-foreground">
            Where personal data is stored or processed outside India, such processing will follow restrictions and
            conditions notified under the DPDPA and related rules from time to time, including any requirements for
            transfers to trusted jurisdictions or contractual safeguards.
          </p>
        </Section>
      </main>

      <footer className="border-t border-border mt-16">
        <div className="mx-auto max-w-3xl px-6 py-8 flex items-center justify-between text-sm text-muted-foreground">
          <span>&copy; {new Date().getFullYear()} {COMPANY_NAME}</span>
          <Link href="/terms" className="hover:text-foreground transition-colors">
            Terms of Service
          </Link>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="font-display text-xl font-semibold mb-3 text-foreground">{title}</h2>
      <div className="text-muted-foreground leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

function Subheading({ children }: { children: React.ReactNode }) {
  return <h3 className="font-semibold text-foreground mt-4 mb-1">{children}</h3>;
}

function DataTable() {
  const rows: { data: string; purpose: string; sensitive: string; retention: string }[] = [
    {
      data: "Full name, email, phone",
      purpose: "Account creation and profile",
      sensitive: "No",
      retention: "While account is active, plus 12 months after closure",
    },
    {
      data: "Face photos and derived face data",
      purpose: "Attendance verification",
      sensitive: "Yes — explicit consent",
      retention: "Until you withdraw consent or delete your account (then erased within 30 days)",
    },
    {
      data: "Identity documents (if your institution collects them)",
      purpose: "Identity verification and fraud prevention",
      sensitive: "Yes — per institution process",
      retention: "As required for the purpose or by law; deleted or minimised when no longer needed",
    },
    {
      data: "Camera (live preview)",
      purpose: "Face registration and attendance capture",
      sensitive: "No — processed on device",
      retention: "Not stored as persistent video",
    },
    {
      data: "Location (when permitted)",
      purpose: "Campus proximity checks for attendance",
      sensitive: "No — in-session only",
      retention: "Not stored on our servers",
    },
    {
      data: "Google sign-in session data",
      purpose: "Authentication when you choose Google",
      sensitive: "No",
      retention: "Session lifetime only",
    },
    {
      data: "Server logs (IP, device, app version)",
      purpose: "Security and debugging",
      sensitive: "No",
      retention: "90 days",
    },
  ];

  return (
    <figure className="mb-10">
      <figcaption className="mb-3 text-sm font-medium text-foreground">
        Summary of personal data categories
      </figcaption>
      <div className="overflow-x-auto rounded-xl border border-border bg-card shadow-sm">
        <table className="w-full min-w-[36rem] table-fixed border-collapse text-left text-sm">
          <colgroup>
            <col className="w-[26%]" />
            <col className="w-[28%]" />
            <col className="w-[22%]" />
            <col className="w-[24%]" />
          </colgroup>
          <thead>
            <tr className="border-b border-border bg-muted/40">
              <th scope="col" className="px-3 py-3 align-bottom text-xs font-semibold uppercase tracking-wide text-muted-foreground sm:px-4">
                Data type
              </th>
              <th scope="col" className="px-3 py-3 align-bottom text-xs font-semibold uppercase tracking-wide text-muted-foreground sm:px-4">
                Purpose
              </th>
              <th scope="col" className="px-3 py-3 align-bottom text-xs font-semibold uppercase tracking-wide text-muted-foreground sm:px-4">
                Sensitive / consent
              </th>
              <th scope="col" className="px-3 py-3 align-bottom text-xs font-semibold uppercase tracking-wide text-muted-foreground sm:px-4">
                Retention
              </th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr
                key={row.data}
                className={`border-b border-border last:border-b-0 ${i % 2 === 1 ? "bg-muted/15" : ""}`}
              >
                <th
                  scope="row"
                  className="px-3 py-3 align-top font-semibold text-foreground sm:px-4 break-words"
                >
                  {row.data}
                </th>
                <td className="px-3 py-3 align-top text-muted-foreground sm:px-4 break-words leading-snug">
                  {row.purpose}
                </td>
                <td className="px-3 py-3 align-top sm:px-4">
                  <span
                    className={`inline-block max-w-full break-words rounded-full px-2.5 py-1 text-center text-[11px] font-semibold leading-tight ${
                      row.sensitive.startsWith("Yes")
                        ? "bg-amber-100 text-amber-900 dark:bg-amber-950/50 dark:text-amber-200"
                        : "bg-muted text-muted-foreground"
                    }`}
                  >
                    {row.sensitive}
                  </span>
                </td>
                <td className="px-3 py-3 align-top text-muted-foreground sm:px-4 break-words leading-snug">
                  {row.retention}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </figure>
  );
}
